RESERVED_CODES={"users",
"links",
"analytics",
"admin",
"docs",
"redoc",
"openapi.json",
"health",
"login",
"logout",
"refresh",
"qr",
"api",
"r"}

MAX_LINKS_PER_MINUTE = 10
MAX_REDIRECTS_PER_MINUTE = 30
RATE_LIMIT_WINDOW_SECONDS = 60
MAX_REDIRECTS_PER_MINUTE_SAME_URL=10
MAX_LOGIN_PER_MINUTE=5
MAX_WRONG_LOGIN=5
MAX_REGISTER_EMAIL_PER_MINUTE=2
MAX_REGISTER_IP_PER_MINUTE=5
MAX_WRONG_REFRESH_TOKEN=15
MAX_REFRESH_PER_MINUTE=10