"""add expires_at,description and is_active to links

Revision ID: 06070522ebc1
Revises: f3b49a0e3109
Create Date: 2026-07-04 16:50:35.497119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06070522ebc1'
down_revision: Union[str, Sequence[str], None] = 'f3b49a0e3109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('links', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('links', sa.Column('description', sa.Text(), nullable=True))

    op.execute("UPDATE links SET is_active = true WHERE is_active IS NULL")

    op.alter_column('links', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'description')
    op.drop_column('links', 'expires_at')
    op.drop_column('links', 'is_active')
    # ### end Alembic commands ###
