"""add server default datetime to tabels

Revision ID: 81f42f1c3ba2
Revises: 5c32dfa6c5b4
Create Date: 2026-07-05 14:50:10.889208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f42f1c3ba2'
down_revision: Union[str, Sequence[str], None] = '5c32dfa6c5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    "refresh_tokens",
    "created_at",
    server_default=sa.text("CURRENT_TIMESTAMP")
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
