"""add created_at to users

Revision ID: ade4f7309542
Revises: 06070522ebc1
Create Date: 2026-07-05 08:56:06.641851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade4f7309542'
down_revision: Union[str, Sequence[str], None] = '06070522ebc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('links', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('links', 'updated_at')
    op.drop_column('links', 'created_at')
    # ### end Alembic commands ###
