"""add roles to user table

Revision ID: afa61a5727e3
Revises: 81f42f1c3ba2
Create Date: 2026-07-06 09:49:20.522201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa61a5727e3'
down_revision: Union[str, Sequence[str], None] = '81f42f1c3ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('User', 'Admin', name='userroles')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column('role', role_enum, nullable=True)
    )

    op.execute("UPDATE users SET role = 'User' WHERE role IS NULL")

    op.alter_column(
        'users',
        'role',
        nullable=False,
        existing_type=role_enum
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('User', 'Admin', name='userroles')

    op.drop_column('users', 'role')

    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
