"""add casecade to Link table

Revision ID: f3b49a0e3109
Revises: 922676218968
Create Date: 2026-07-03 16:38:36.245377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b49a0e3109'
down_revision: Union[str, Sequence[str], None] = '922676218968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('click_logs_link_id_fkey'), 'click_logs', type_='foreignkey')
    op.create_foreign_key(None, 'click_logs', 'links', ['link_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'click_logs', type_='foreignkey')
    op.create_foreign_key(op.f('click_logs_link_id_fkey'), 'click_logs', 'links', ['link_id'], ['id'])
    # ### end Alembic commands ###
