
upstream url_cluster {
    least_conn;#algorithm
    server  url_shortener:8000;
}
include mime.types;
limit_req_zone $binary_remote_addr zone=global_limit:10m rate=30r/s;
server {
        listen 80;
        server_name go.weetis.com www.go.weetis.com;
        #Buradaki headerlar response eklenip browsera veriliyor
        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
        # Tüm API için IP başına saniyede max 30 istek (Anormal bot saldırılarını önler)
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            limit_req zone=global_limit burst=20 nodelay;#set rate limiting to all endpoints
            proxy_pass http://url_cluster;
            #Buradaki headarlar requeste eklenip uygulamaya geliyor
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Connection "";

        }
    }
