name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env.docker
        run: |
             echo "SECRET_KEY=ŞSDKFSFJSŞDFUJSOIAFSIFJSKDFJASŞLDK" >> .env.docker
             echo "ALGORITHM=HS256" >> .env.docker
             echo  "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env.docker
             echo "REFRESH_TOKEN_EXPIRE_DAYS=30" >> .env.docker
             echo "DATABASE_URL=postgresql://postgres:12345@postgres:5432/url_shortener" >> .env.docker
             echo "TEST_DATABASE_URL=postgresql://postgres:12345@postgres:5432/test_url_database" >> .env.docker
             echo "BASE_URL=http://localhost:8000" >> .env.docker
             echo "REDIS_HOST=redis_test" >> .env.docker
             echo  "REDIS_PORT=6379" >> .env.docker
             echo "TZ=Europe/Istanbul " >> .env.docker
      - name: Create .env.test
        run: |
             echo "SECRET_KEY=ŞSDKFSFJSŞDFUJSOIAFSIFJSKDFJASŞLDK" >> .env.test
             echo "ALGORITHM=HS256" >> .env.test
             echo  "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env.test
             echo "REFRESH_TOKEN_EXPIRE_DAYS=30" >> .env.test
             echo "DATABASE_URL=postgresql://postgres:12345@postgres:5432/url_shortener" >> .env.test
             echo "TEST_DATABASE_URL=postgresql://postgres:12345@postgres:5432/test_url_database" >> .env.test
             echo "BASE_URL=http://localhost:8000" >> .env.test
             echo "REDIS_HOST=redis_test" >> .env.test
             echo  "REDIS_PORT=6379" >> .env.test
      - name: Run docker 
        run: docker compose up -d postgres redis_test
    
      - name: Wait postgres
        run: |
          until docker exec postgres pg_isready -U postgres; do
            sleep 2
            done
      - name:  Create test database
        run: docker exec postgres psql -U postgres -d postgres -c "CREATE DATABASE test_url_database;"
      - name: Run tests
        run: docker compose run --rm test
      - name: Stop containers
        if: always()
        run: docker compose down -v