name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      ALGORITHM: ${{ vars.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}
      REFRESH_TOKEN_EXPIRE_DAYS: ${{ vars.REFRESH_TOKEN_EXPIRE_DAYS }}
      BASE_URL: ${{ vars.BASE_URL }}
      REDIS_HOST: ${{ vars.REDIS_HOST }}
      REDIS_PORT: ${{ vars.REDIS_PORT }}
      TZ: ${{ vars.TZ }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Create .env.test
        run: |
             echo "SECRET_KEY=$SECRET_KEY" >> .env.test
              echo "ALGORITHM=$ALGORITHM" >> .env.test
              echo "ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES" >> .env.test
              echo "REFRESH_TOKEN_EXPIRE_DAYS=$REFRESH_TOKEN_EXPIRE_DAYS" >> .env.test
              echo "DATABASE_URL=$DATABASE_URL" >> .env.test
              echo "TEST_DATABASE_URL=$TEST_DATABASE_URL" >> .env.test
              echo "BASE_URL=$BASE_URL" >> .env.test
              echo "REDIS_HOST=$REDIS_HOST" >> .env.test
              echo "REDIS_PORT=$REDIS_PORT" >> .env.test
              echo "TZ=$TZ" >> .env.test
              echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env.test
              echo "POSTGRES_USER=$POSTGRES_USER" >> .env.test
              echo "POSTGRES_DB=$POSTGRES_DB" >> .env.test
      - name: Run docker 
        run: docker compose -f compose.test.yml up -d postgres redis_test
   
      
      - name: Wait postgres
        run: |
          until docker exec postgres pg_isready -U postgres; do
            sleep 2
            done

      - name:  Create test database
        run: docker exec postgres psql -U postgres -d postgres -c "CREATE DATABASE url_shortener;"
      - name: Run tests
        run: docker compose -f compose.test.yml run --rm test
      - name: Stop containers
        if: always()
        run: docker compose -f compose.test.yml  down -v